name: mcq_exam_app
description: A highly secure MCQ Exam App for Teachers and Students.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.3
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  
  # AI Integration
  google_generative_ai: ^0.4.7
  
  # Security (Anti-Cheat)
  safe_device: ^1.1.4 # For Root/Jailbreak detection
  wakelock_plus: ^1.1.4 # To keep screen awake during exam

  # Utilities
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.1.0
  file_picker: ^10.3.2
  syncfusion_flutter_pdf: ^28.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
