// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQSs65PhL_hjecD75HzZp18aF7kY_WsDo',
    appId: '1:673970899276:web:5e99f8778dff37684227e9',
    messagingSenderId: '673970899276',
    projectId: 'mcq-app-67b4b',
    authDomain: 'mcq-app-67b4b.firebaseapp.com',
    storageBucket: 'mcq-app-67b4b.firebasestorage.app',
    measurementId: 'G-R6LS37GDN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8HRpjUFh1iYioSbsPk_nuH-IFMKWoRRw',
    appId: '1:673970899276:android:d365f69e053071cc4227e9',
    messagingSenderId: '673970899276',
    projectId: 'mcq-app-67b4b',
    storageBucket: 'mcq-app-67b4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcde2ZrMd7jdVqGd2P7GcylDtDZhkeA8o',
    appId: '1:673970899276:ios:0c1d74559a8a659b4227e9',
    messagingSenderId: '673970899276',
    projectId: 'mcq-app-67b4b',
    storageBucket: 'mcq-app-67b4b.firebasestorage.app',
    iosBundleId: 'com.mcqexam.mcqExamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcde2ZrMd7jdVqGd2P7GcylDtDZhkeA8o',
    appId: '1:673970899276:ios:0c1d74559a8a659b4227e9',
    messagingSenderId: '673970899276',
    projectId: 'mcq-app-67b4b',
    storageBucket: 'mcq-app-67b4b.firebasestorage.app',
    iosBundleId: 'com.mcqexam.mcqExamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQSs65PhL_hjecD75HzZp18aF7kY_WsDo',
    appId: '1:673970899276:web:03ad24ed5999df744227e9',
    messagingSenderId: '673970899276',
    projectId: 'mcq-app-67b4b',
    authDomain: 'mcq-app-67b4b.firebaseapp.com',
    storageBucket: 'mcq-app-67b4b.firebasestorage.app',
    measurementId: 'G-8RSRDY2LZE',
  );
}
